name: main
on: [push, pull_request]
jobs:
  notify:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: eslint

      - name: Run tests
        run: npm test

      - name: Slack notification
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}